# REF: https://docs.docker.com/engine/reference/builder/
# build: docker build -t touch-proto .
FROM alpine:latest

WORKDIR /tmp

# run: docker run --rm -v $PWD:/tmp touch-proto helloworld
ENTRYPOINT [ "touch" ]
