name: Markdownlint Action
on: push

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - uses: nosborn/github-action-markdown-cli@v3.3.0
      name: Markdownlint
      with:
        files: .
        config_file: ".markdownlint.json"
