name: Markdownlint Action
on: push

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: nosborn/github-action-markdown-cli@v3.3.0
      name: Markdownlint
      with:
        files: .
        config_file: ".markdownlint.json"
