name: Markdownlint Action
on: push

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: nosborn/github-action-markdown-cli@v3.3.0
      name: Markdownlint
      with:
        files: .
        config_file: ".markdownlint.json"
