name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: rojopolis/spellcheck-github-actions@0.38.0
=======
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@0.41.0
>>>>>>> 024796f139ee1630f7f2c58aad7fe8cba3f2403d
      name: Spellcheck

